### ISSUE TITLE
Add Direct Lookup for Getty Vocabs

### ISSUE THREAD

**Issue by sfolsom** [cul-it/qa_server#384]
To get back RDF from Getty's APIs, it seems like we need to use their SPARQL API, but SPARQL may not be great for generic keyword searching.

Samvera code base has Getty lookups, maybe this is something we can turn on:

- https://github.com/samvera/questioning_authority/wiki/Connecting-to-Getty
- https://github.com/samvera/questioning_authority/tree/main/lib/qa/authorities/getty

**Comment by chrisrlc** [comment]
Current attempt at creating a linked data authority config for getty is deployed to: https://lookup-int.ld4l.org/

There is currently one getty_direct endpoint, with aat, tgn and ulan as required subauthorities to be specified in the url. For example:

- Retrieval by term id:
  - aat: https://lookup-int.ld4l.org/authorities/show/linked_data/getty_direct/aat/300264973
  - tgn: https://lookup-int.ld4l.org/authorities/show/linked_data/getty_direct/tgn/2188773
  - ulan: https://lookup-int.ld4l.org/authorities/show/linked_data/getty_direct/ulan/500304715
- Search:
  - aat: https://lookup-int.ld4l.org/authorities/search/linked_data/getty_direct/aat?q=amphora
  - tgn:  https://lookup-int.ld4l.org/authorities/search/linked_data/getty_direct/tgn?q=Gouverneur
  - ulan: https://lookup-int.ld4l.org/authorities/search/linked_data/getty_direct/ulan?q=chicago%20library

To review all current testing scenarios and figure out which changes we're okay with vs which ones we need to try to handle better: https://lookup-int.ld4l.org/check_status?utf8=%E2%9C%93&authority=GETTY_DIRECT&compare_with=&validation_type=accuracy
- All test terms, queries, and expected positions were copied from the getty ld4 cached lookup scenarios, except I used the singular form of "serpentiforme" and "residuo tóxico".
- 3 test cases fail (expected term not found in results) because the full query isn't found in the prefLabel:
    - "gestabiliseerd": returns only "gestabiliseerd zand", not the expected nl-alt label form of "[stabilizing](https://vocab.getty.edu/aat/300163757)"
    - "Boulder, CO": a search for just "Boulder" will retrieve the expected term
    - "Paris, France": interestingly, a search in [getty vocab's UI](https://vocab.getty.edu/resource/getty/search?q=Paris%2C+France&luceneIndex=Brief&indexDataset=Any&_form=%2Ftgn%2F2000198) doesn't return the expected term either, but a search for just "Paris" includes the expected term in results.
- An example SPARQL for search: [query=amphora, subauth=aat ](https://vocab.getty.edu/queries?toc=Finding_Subjects&query=CONSTRUCT+%7B%3Fs+dc%3Aidentifier+%3Fid%3B+skos%3AprefLabel+%3FprefLabel.%7D%0AWHERE+%7B%3Fs+a+skos%3AConcept%3B+luc%3Aterm+%22amphora%22%3B+skos%3AinScheme+aat%3A%3B+skos%3AprefLabel+%3FprefLabel.%0A++%3Fs+dc%3Aidentifier+%3Fid.%0A++BIND%28REPLACE%28%22amphora%22%2C+%22%5B%2C*%28%29%5D%22%2C+%22%22%2C+%22i%22%29+AS+%3Fstripped_query%29.%0A++BIND%28REPLACE%28%3Fstripped_query%2C+%22%28%5C%5CS%2B%29%5C%5Cs*%22%2C+%22%28%3F%3D.*%241%29%22%29+AS+%3Ffilter_query%29.%0A++FILTER+regex%28str%28%3FprefLabel%29%2C+%3Ffilter_query%2C+%22i%22%29.%0A%7D+ORDER+BY+asc%28lcase%28str%28%3FprefLabel%29%29%29&implicit=true&equivalent=false#Finding_Subjects)
   - Extra context if you're interested: I'm using some hacks to try to preprocess the user query for search. Part of this is a workaround for ensuring that we can pull non-english/non-latin script results as expected, despite the fact that getty wants different query handling for different languages. We can try to keep tweaking this query, but if we get to a point where we're still not getting the results we need, we may have to see if we get better results by extending the alternative non-linked data parsing endpoint from the samvera qa gem: https://lookup-int.ld4l.org/authorities/search/getty/aat?q=amphora (note: we would still have to tweak the sparql query used in this endpoint, as you can see from the lack of results for "Paris, France": https://lookup-int.ld4l.org/authorities/search/getty/tgn?q=Paris,%20France).

Sorting is currently ascending by prefLabel and can be tweaked in [the sparql query](https://vocab.getty.edu/queries?toc=Finding_Subjects&query=CONSTRUCT+%7B%3Fs+dc%3Aidentifier+%3Fid%3B+skos%3AprefLabel+%3FprefLabel.%7D%0AWHERE+%7B%3Fs+a+skos%3AConcept%3B+luc%3Aterm+%22amphora%22%3B+skos%3AinScheme+aat%3A%3B+skos%3AprefLabel+%3FprefLabel.%0A++%3Fs+dc%3Aidentifier+%3Fid.%0A++BIND%28REPLACE%28%22amphora%22%2C+%22%5B%2C*%28%29%5D%22%2C+%22%22%2C+%22i%22%29+AS+%3Fstripped_query%29.%0A++BIND%28REPLACE%28%3Fstripped_query%2C+%22%28%5C%5CS%2B%29%5C%5Cs*%22%2C+%22%28%3F%3D.*%241%29%22%29+AS+%3Ffilter_query%29.%0A++FILTER+regex%28str%28%3FprefLabel%29%2C+%3Ffilter_query%2C+%22i%22%29.%0A%7D+ORDER+BY+asc%28lcase%28str%28%3FprefLabel%29%29%29&implicit=true&equivalent=false#Finding_Subjects).

**Comment by sfolsom** [comment]
Looks good in Sinopia as-is. We can reopen if something comes up.
